# # -----------------------Development-----------------------
version: '2'

services:  
  cdn:
    image: node:latest
    build: .
    command: npm run dev
    ports:
      - '2000:2000'
    volumes_from:
      - 'cdn-data'
    volumes:
      - '.:/usr/src/app'
      - 'cdn-deps:/usr/src/app/node_modules'

  cdn-data:
    image: node:latest
    entrypoint: '/bin/bash'
    container_name: cdn-data
    volumes:
     - './static-media:/static-media'

volumes: 
  cdn-deps:
  # cdn-data:

# ----------------------Production ---------------------------------

# version: '2'

# version: '2'

# services:
#   db:
#     image: mysql
#     container_name: mysql-server
#     ports:
#       - "3306:3306"
#     environment:
#       MYSQL_ROOT_PASSWORD: 123456
#       MYSQL_USER: dev
#       MYSQL_PASSWORD: 123456
#       MYSQL_DATABASE: database1
#     volumes:
#       - '.backup/var/lib/mysql:/var/lib/mysql'
#   api:
#     build: .
#     command: npm run dev
#     ports:
#       - '4000:4000'
#     # links:
#     #   - db
#     depends_on:
#       - db
#     volumes:
#       - '.:/usr/src/app'
#       - 'api-deps:/usr/src/app/node_modules'
# volumes: 
#   api-deps:
#   db-data:


